# Docker Compose 
version: '3.0'

# Define services
services:
  # symfony service
  symfony:
    image: akryos/camp_symfony
    ports:
      - "64:80" 
    container_name: camp_symf_cont_damien
    depends_on:
      - database
    restart: always
    environment:
      DATABASE_URL: "mysql://root:pass_123+@database:3306/amssymfonyv2?serverVersion=mariadb-10.4.11"
    networks:
      - camp_net

  # Database Service(Mysql)
  database:
    image: mysql
    container_name: camp_symf_db_damien
    volumes:
       - db_camp:/var/lib/mysql 
    restart: always
    environment:
      MYSQL_DATABASE: amssymfonyv2
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass_123+    
    networks:
      - camp_net

  # phpmyadmin Service 
  phpmyadmin:
    image: phpmyadmin
    container_name: camp_symf_phpad_damien
    depends_on:
      - database
    restart: always
    ports:
      - 4404:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - camp_net

# Dec vol
volumes:
   db_camp:

# Dec net
networks:
  camp_net:


